aws_region: eu-west-2

cluster_name: takeon-dev-eks-cluster
namesapce: takeon-dev

ecr_repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/takeon-ui-cicd
git_repository: https://github.com/ONSdigital/takeon-ui
