aws_access_key_id: 
aws_secret_access_key: 
aws_region: eu-west-2

cluster_name: Take-On-Temp
release: ryan-cicd-test

ecr_repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/takeon-ui-cicd
git_repository: https://github.com/ONSdigital/takeon-ui
