resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.13"

resources:
  - name: git-repo
    type: git
    source:
      uri: {{git_repository}}
      branch: master
  - name: docker-config
    type: docker-image
    source:
      repository: {{ecr_repository}}
      aws_access_key_id: {{aws_access_key_id}}
      aws_secret_access_key: {{aws_secret_access_key}}
  - name: kubeconfig-file
    type: s3
    source:
      bucket: cicd-kubeconfig
      versioned_file: kube_config.yaml
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      region_name: {{aws_region}}
  - name: k8s
    type: kubernetes
    source:
      use_aws_iam_authenticator: true
      aws_eks_cluster_name: {{cluster_name}}
      aws_access_key_id: {{aws_access_key_id}}
      aws_secret_access_key: {{aws_secret_access_key}}
      namespace: cicd-test

jobs:
  - name: "Docker-Build"
    public: false
    plan:
      - get: git-repo
        trigger: true
      - put: docker-config
        params:
          # The path of a directory containing a Dockerfile to build
          build: git-repo
          tag_as_latest: true
  - name: "Deploy-Application"
    public: false
    plan:
      - aggregate:
        - get: docker-config
          trigger: true
          # When specified, only the versions of the resource
          # that made it through the given list of jobs will be considered when
          # triggering and fetching.
          passed:
            - "Docker-Build"
        - get: kubeconfig-file
      - put: k8s
        params:
          kubectl: delete pods -l app=ui-cicd -n cicd-test
          wait_until_ready_selector: app=ui-cicd
          kubeconfig_file: kubeconfig-file/kube_config.yaml
